export const styles = {
  hide: {
    opacity: 0,
    transition: "all 1ms ease-in",
    transitionProperty: "opacity, width",
    width: "0%",
    position: "absolute",
    left: "0px",
    top: "28px",
    backgroundColor: "lightGrey",
  },
  show: {
    opacity: 1,
    width: "100%",
    transition: "all 1ms ease-in",
    transitionProperty: "opacity,width",
    position: "absolute",
    left: "0px",
    top: "29px",
    boxShadow: "0 4px 17px 6px rgb(0 0 0 / 10%)",
    zIndex: "1",
    backgroundColor: "#f5f6f8",
    backgroundColor: "#3e3e3e",
    borderBottomLeftRadius: "6px",
    borderBottomRightRadius: "6px",
    boxShadow: "rgb(100 100 100 / 30%) 0px 0px 2px 1px",
  },
  workMode: {
    border: "3px solid #ff4d4f",
    backgroundColor: "rgb(17, 17, 17)",
    color: "#111 !important",
    boxShadow: "rgb(100 100 100 / 30%) 0px 0px 2px 1px",
  },
  restMode: {
    backgroundColor: "rgb(17, 17, 17)",
    border: "3px solid rgb(0, 200, 117)",
    color: "#111 !important",
    boxShadow: "rgb(100 100 100 / 30%) 0px 0px 2px 1px",
  },
  size: {
    fontSize: "21px",
    fontWeight: "bolder",
    display: "inline",
  },
};
